"""Q-Orca OpenQASM 3.0 compiler — compiles QMachineDef → OpenQASM 3.0."""

from q_orca.ast import QMachineDef, QuantumGate
from q_orca.noise import resolve_noise_section
from q_orca.compiler.qiskit import _build_angle_context, _parse_effect_string, _infer_bit_count
from q_orca.compiler.parametric import expand_action_call
from q_orca.compiler.util import (
    infer_qubit_count as _infer_qubit_count,
    format_assertion_expr as _format_assertion_expr,
    state_label as _state_label,
    ComposedMachineError,
    machine_has_invoke,
)


def compile_to_qasm(machine: QMachineDef) -> str:
    if machine_has_invoke(machine):
        raise ComposedMachineError(machine.name)

    lines = []

    lines.append("// Generated by Q-Orca compiler")
    lines.append(f"// Machine: {machine.name}")
    has_context_update = any(a.context_update is not None for a in machine.actions)
    if has_context_update:
        lines.append(
            "// NOTE: context-update actions are annotations only; "
            "shot-to-shot execution not yet implemented."
        )
    # Noise model: QASM 3 has no native noise grammar, so emit the section as a
    # stable, machine-parseable `// noise:` comment block (no semantic effect).
    noise_section = resolve_noise_section(machine)
    if noise_section is not None and noise_section.channels:
        lines.append("// noise: (declarative; not simulated from QASM)")
        for ch in noise_section.channels:
            params = " ".join(f"{k}={v}" for k, v in ch.parameters.items())
            lines.append(f"// noise: channel={ch.kind} target={ch.target.raw} {params}".rstrip())

    lines.append('OPENQASM 3.0;')
    lines.append('include "stdgates.inc";')
    lines.append("")

    qubit_count = _infer_qubit_count(machine)
    bit_count = _infer_bit_count(machine)
    lines.append(f"qubit[{qubit_count}] q;")

    has_measurement = any(a.measurement for a in machine.actions)
    has_mid_circuit = any(a.mid_circuit_measure is not None for a in machine.actions)
    has_measure_event = any(
        "measure" in e.name.lower() or "collapse" in e.name.lower()
        for e in machine.events
    )
    if has_mid_circuit and bit_count > 0:
        lines.append(f"bit[{bit_count}] c;")
        lines.append("")
    elif has_measurement or has_measure_event:
        lines.append(f"bit[{qubit_count}] c;")
        lines.append("")

    for field in machine.context:
        if hasattr(field.type, "kind") and field.type.kind == "int":
            default = f" = {field.default_value}" if field.default_value else ""
            lines.append(f"int {field.name}{default};")
    if any(hasattr(f.type, "kind") and f.type.kind == "int" for f in machine.context):
        lines.append("")

    action_map = {a.name: a for a in machine.actions}
    gate_sequence = _extract_gate_sequence(machine)

    # Per-state assertion comments (out-of-band; no instructions). Emitted
    # immediately before the gate sequence of the first outgoing transition out
    # of each annotated state; states with no outgoing transition are flushed
    # after the sequence.
    assertions_by_state = {s.name: s.assertions for s in machine.states if s.assertions}
    emitted_probes: set[str] = set()

    def _emit_qasm_assert(state_name: str) -> None:
        for a in assertions_by_state[state_name]:
            lines.append(
                f"// assert: {_format_assertion_expr(a, 'q')} "
                f"@ state {_state_label(state_name)}"
            )
        emitted_probes.add(state_name)

    lines.append("// Gate sequence derived from state machine transitions")
    for action_name, gates, comment in gate_sequence:
        source = comment.split(" --", 1)[0] if comment and " --" in comment else None
        if source in assertions_by_state and source not in emitted_probes:
            _emit_qasm_assert(source)
        if comment:
            lines.append(f"// {comment}")
        action = action_map.get(action_name)
        if action and action.mid_circuit_measure is not None:
            mcm = action.mid_circuit_measure
            lines.append(f"c[{mcm.bit_idx}] = measure q[{mcm.qubit_idx}];")
        elif action and action.conditional_gate is not None:
            cg = action.conditional_gate
            gate_str = _gate_to_qasm(cg.gate, qubit_count).rstrip(";")
            # OpenQASM 3.0 per-bit conditional: bare bit for 1, negated for 0.
            # Compound conditions join clauses with `&&` (short-circuit AND).
            clauses = [
                (f"c[{bit_idx}]" if value else f"!c[{bit_idx}]")
                for bit_idx, value in cg.conditions
            ]
            cond = " && ".join(clauses)
            lines.append(f"if ({cond}) {{ {gate_str}; }}")
        elif action and action.context_update is not None:
            raw = action.context_update.raw or action.effect or ""
            lines.append(f"// context_update: {raw}")
        else:
            for gate in gates:
                lines.append(_gate_to_qasm(gate, qubit_count))

    # Flush assertions for annotated states never visited as a transition
    # source (e.g. [final] states).
    for s in machine.states:
        if s.name in assertions_by_state and s.name not in emitted_probes:
            _emit_qasm_assert(s.name)

    # Emit terminal measurement block only when there are no mid-circuit
    # measurements (which are emitted inline in the gate sequence above).
    if not has_mid_circuit and (has_measurement or has_measure_event):
        lines.append("")
        lines.append("// Measurement")
        for i in range(qubit_count):
            lines.append(f"c[{i}] = measure q[{i}]; // {i}")

    return "\n".join(lines)


def _extract_gate_sequence(machine: QMachineDef) -> list:
    """Return (action_name, [gates], comment) triples ordered by BFS traversal."""
    steps = []
    action_map = {a.name: a for a in machine.actions}
    angle_context = _build_angle_context(machine)

    initial = next((s for s in machine.states if s.is_initial), None)
    if not initial:
        return steps

    visited = set()
    queue = [initial.name]

    while queue:
        current = queue.pop(0)
        if current in visited:
            continue
        visited.add(current)

        outgoing = [t for t in machine.transitions if t.source == current]

        for t in outgoing:
            if t.action:
                action = action_map.get(t.action)
                if action:
                    effect = (
                        expand_action_call(action, t.bound_arguments)
                        if t.bound_arguments is not None
                        else action.effect
                    )
                    # Parse the full effect string (handles CX, multi-gate, etc.)
                    gates = _parse_effect_string(effect, angle_context=angle_context) if effect else []
                    # Fall back to the single gate stored on the action if parsing gave nothing
                    if not gates and action.gate:
                        gates = [action.gate]
                    steps.append((t.action, gates, f"{t.source} -> {t.target} via {t.event}"))

            # Continue BFS past mid-circuit measurement events; stop only at
            # terminal (end-of-circuit) measurement events.
            transition_action = action_map.get(t.action) if t.action else None
            is_mid_circuit = (
                transition_action is not None
                and transition_action.mid_circuit_measure is not None
            )
            is_terminal_measure = (
                ("measure" in t.event.lower() or "collapse" in t.event.lower())
                and not is_mid_circuit
            )
            if not is_terminal_measure and t.target not in visited:
                queue.append(t.target)

    return steps


def _gate_to_qasm(gate: QuantumGate, qubit_count: int) -> str:
    def t(idx):
        return f"q[{idx}]"

    mapping = {
        "H": lambda: f"h {t(gate.targets[0])};",
        "X": lambda: f"x {t(gate.targets[0])};",
        "Y": lambda: f"y {t(gate.targets[0])};",
        "Z": lambda: f"z {t(gate.targets[0])};",
        "T": lambda: f"t {t(gate.targets[0])};",
        "S": lambda: f"s {t(gate.targets[0])};",
    }

    if gate.kind in mapping:
        return mapping[gate.kind]()

    if gate.kind == "CNOT":
        ctrl = gate.controls[0] if gate.controls else 0
        return f"cx {t(ctrl)}, {t(gate.targets[0])};"
    if gate.kind == "CZ":
        ctrl = gate.controls[0] if gate.controls else 0
        return f"cz {t(ctrl)}, {t(gate.targets[0])};"
    if gate.kind == "SWAP":
        return f"swap {t(gate.targets[0])}, {t(gate.targets[1] if len(gate.targets) > 1 else 1)};"
    if gate.kind == "Rx":
        return f"rx({gate.parameter or 0}) {t(gate.targets[0])};"
    if gate.kind == "Ry":
        return f"ry({gate.parameter or 0}) {t(gate.targets[0])};"
    if gate.kind == "Rz":
        return f"rz({gate.parameter or 0}) {t(gate.targets[0])};"
    if gate.kind == "CCNOT":
        ctrls = gate.controls or [0, 1]
        return f"ccx {t(ctrls[0])}, {t(ctrls[1] if len(ctrls) > 1 else 1)}, {t(gate.targets[0])};"
    if gate.kind == "CCZ":
        ctrls = gate.controls or [0, 1]
        c0 = ctrls[0]
        c1 = ctrls[1] if len(ctrls) > 1 else 1
        tgt = gate.targets[0]
        return f"h {t(tgt)}; ccx {t(c0)}, {t(c1)}, {t(tgt)}; h {t(tgt)};"
    if gate.kind == "MCX":
        ctrls = gate.controls or []
        n = len(ctrls)
        args = ", ".join(t(i) for i in list(ctrls) + [gate.targets[0]])
        return f"ctrl({n}) @ x {args};"
    if gate.kind == "MCZ":
        ctrls = gate.controls or []
        n = len(ctrls)
        tgt = gate.targets[0]
        args = ", ".join(t(i) for i in list(ctrls) + [tgt])
        return f"h {t(tgt)}; ctrl({n}) @ x {args}; h {t(tgt)};"
    if gate.kind == "CSWAP":
        ctrl = gate.controls[0] if gate.controls else 0
        return f"cswap {t(ctrl)}, {t(gate.targets[0])}, {t(gate.targets[1] if len(gate.targets) > 1 else 2)};"
    # Two-qubit parameterized gates — CRx/CRy/CRz are in stdgates.inc; RXX/RYY/RZZ are decomposed
    if gate.kind == "CRx":
        ctrl = gate.controls[0] if gate.controls else 0
        return f"crx({gate.parameter or 0}) {t(ctrl)}, {t(gate.targets[0])};"
    if gate.kind == "CRy":
        ctrl = gate.controls[0] if gate.controls else 0
        return f"cry({gate.parameter or 0}) {t(ctrl)}, {t(gate.targets[0])};"
    if gate.kind == "CRz":
        ctrl = gate.controls[0] if gate.controls else 0
        return f"crz({gate.parameter or 0}) {t(ctrl)}, {t(gate.targets[0])};"
    if gate.kind == "RZZ":
        # RZZ(θ) q0,q1 → cx q0,q1; rz(θ) q1; cx q0,q1;
        q0 = gate.targets[0]
        q1 = gate.targets[1] if len(gate.targets) > 1 else 1
        theta = gate.parameter or 0
        return f"cx {t(q0)}, {t(q1)}; rz({theta}) {t(q1)}; cx {t(q0)}, {t(q1)};"
    if gate.kind == "RXX":
        # RXX(θ) q0,q1 → h q0; h q1; cx q0,q1; rz(θ) q1; cx q0,q1; h q0; h q1;
        q0 = gate.targets[0]
        q1 = gate.targets[1] if len(gate.targets) > 1 else 1
        theta = gate.parameter or 0
        return (
            f"h {t(q0)}; h {t(q1)}; cx {t(q0)}, {t(q1)}; "
            f"rz({theta}) {t(q1)}; cx {t(q0)}, {t(q1)}; h {t(q0)}; h {t(q1)};"
        )
    if gate.kind == "RYY":
        # RYY(θ) q0,q1 → rx(pi/2) q0; rx(pi/2) q1; cx q0,q1; rz(θ) q1; cx q0,q1; rx(-pi/2) q0; rx(-pi/2) q1;
        q0 = gate.targets[0]
        q1 = gate.targets[1] if len(gate.targets) > 1 else 1
        theta = gate.parameter or 0
        return (
            f"rx(pi/2) {t(q0)}; rx(pi/2) {t(q1)}; cx {t(q0)}, {t(q1)}; "
            f"rz({theta}) {t(q1)}; cx {t(q0)}, {t(q1)}; rx(-pi/2) {t(q0)}; rx(-pi/2) {t(q1)};"
        )
    if gate.kind == "custom":
        return f"// custom gate: {gate.custom_name or 'unknown'} on {', '.join(t(idx) for idx in gate.targets)};"

    return f"// unknown gate: {gate.kind}"


