"""Q-Orca OpenQASM 3.0 compiler — compiles QMachineDef → OpenQASM 3.0."""

import re

from q_orca.ast import QMachineDef, QuantumGate, QTypeScalar, QTypeList, QTypeQubit
from q_orca.compiler.qiskit import _parse_effect_string


def compile_to_qasm(machine: QMachineDef) -> str:
    lines = []

    lines.append("// Generated by Q-Orca compiler")
    lines.append(f"// Machine: {machine.name}")
    lines.append('OPENQASM 3.0;')
    lines.append('include "stdgates.inc";')
    lines.append("")

    qubit_count = _infer_qubit_count(machine)
    lines.append(f"qubit[{qubit_count}] q;")

    has_measurement = any(a.measurement for a in machine.actions)
    has_measure_event = any(
        "measure" in e.name.lower() or "collapse" in e.name.lower()
        for e in machine.events
    )
    if has_measurement or has_measure_event:
        lines.append(f"bit[{qubit_count}] c;")
        lines.append("")

    for field in machine.context:
        if hasattr(field.type, "kind") and field.type.kind == "int":
            default = f" = {field.default_value}" if field.default_value else ""
            lines.append(f"int {field.name}{default};")
    if any(hasattr(f.type, "kind") and f.type.kind == "int" for f in machine.context):
        lines.append("")

    gate_sequence = _extract_gate_sequence(machine)
    lines.append("// Gate sequence derived from state machine transitions")
    for action_name, gates, comment in gate_sequence:
        if comment:
            lines.append(f"// {comment}")
        for gate in gates:
            lines.append(_gate_to_qasm(gate, qubit_count))

    if has_measurement or has_measure_event:
        lines.append("")
        lines.append("// Measurement")
        for i in range(qubit_count):
            lines.append(f"c[{i}] = measure q[{i}]; // {i}")

    return "\n".join(lines)


def _extract_gate_sequence(machine: QMachineDef) -> list:
    """Return (action_name, [gates], comment) triples ordered by BFS traversal."""
    steps = []
    action_map = {a.name: a for a in machine.actions}

    initial = next((s for s in machine.states if s.is_initial), None)
    if not initial:
        return steps

    visited = set()
    queue = [initial.name]

    while queue:
        current = queue.pop(0)
        if current in visited:
            continue
        visited.add(current)

        outgoing = [t for t in machine.transitions if t.source == current]

        for t in outgoing:
            if t.action:
                action = action_map.get(t.action)
                if action:
                    # Parse the full effect string (handles CX, multi-gate, etc.)
                    gates = _parse_effect_string(action.effect) if action.effect else []
                    # Fall back to the single gate stored on the action if parsing gave nothing
                    if not gates and action.gate:
                        gates = [action.gate]
                    steps.append((t.action, gates, f"{t.source} -> {t.target} via {t.event}"))

            is_measure = "measure" in t.event.lower() or "collapse" in t.event.lower()
            if not is_measure and t.target not in visited:
                queue.append(t.target)

    return steps


def _gate_to_qasm(gate: QuantumGate, qubit_count: int) -> str:
    def t(idx):
        return f"q[{idx}]"

    mapping = {
        "H": lambda: f"h {t(gate.targets[0])};",
        "X": lambda: f"x {t(gate.targets[0])};",
        "Y": lambda: f"y {t(gate.targets[0])};",
        "Z": lambda: f"z {t(gate.targets[0])};",
        "T": lambda: f"t {t(gate.targets[0])};",
        "S": lambda: f"s {t(gate.targets[0])};",
    }

    if gate.kind in mapping:
        return mapping[gate.kind]()

    if gate.kind == "CNOT":
        ctrl = gate.controls[0] if gate.controls else 0
        return f"cx {t(ctrl)}, {t(gate.targets[0])};"
    if gate.kind == "CZ":
        ctrl = gate.controls[0] if gate.controls else 0
        return f"cz {t(ctrl)}, {t(gate.targets[0])};"
    if gate.kind == "SWAP":
        return f"swap {t(gate.targets[0])}, {t(gate.targets[1] if len(gate.targets) > 1 else 1)};"
    if gate.kind == "Rx":
        return f"rx({gate.parameter or 0}) {t(gate.targets[0])};"
    if gate.kind == "Ry":
        return f"ry({gate.parameter or 0}) {t(gate.targets[0])};"
    if gate.kind == "Rz":
        return f"rz({gate.parameter or 0}) {t(gate.targets[0])};"
    if gate.kind == "CCNOT":
        ctrls = gate.controls or [0, 1]
        return f"ccx {t(ctrls[0])}, {t(ctrls[1] if len(ctrls) > 1 else 1)}, {t(gate.targets[0])};"
    if gate.kind == "CSWAP":
        ctrl = gate.controls[0] if gate.controls else 0
        return f"cswap {t(ctrl)}, {t(gate.targets[0])}, {t(gate.targets[1] if len(gate.targets) > 1 else 2)};"
    # Two-qubit parameterized gates — CRx/CRy/CRz are in stdgates.inc; RXX/RYY/RZZ are decomposed
    if gate.kind == "CRx":
        ctrl = gate.controls[0] if gate.controls else 0
        return f"crx({gate.parameter or 0}) {t(ctrl)}, {t(gate.targets[0])};"
    if gate.kind == "CRy":
        ctrl = gate.controls[0] if gate.controls else 0
        return f"cry({gate.parameter or 0}) {t(ctrl)}, {t(gate.targets[0])};"
    if gate.kind == "CRz":
        ctrl = gate.controls[0] if gate.controls else 0
        return f"crz({gate.parameter or 0}) {t(ctrl)}, {t(gate.targets[0])};"
    if gate.kind == "RZZ":
        # RZZ(θ) q0,q1 → cx q0,q1; rz(θ) q1; cx q0,q1;
        q0 = gate.targets[0]
        q1 = gate.targets[1] if len(gate.targets) > 1 else 1
        theta = gate.parameter or 0
        return f"cx {t(q0)}, {t(q1)}; rz({theta}) {t(q1)}; cx {t(q0)}, {t(q1)};"
    if gate.kind == "RXX":
        # RXX(θ) q0,q1 → h q0; h q1; cx q0,q1; rz(θ) q1; cx q0,q1; h q0; h q1;
        q0 = gate.targets[0]
        q1 = gate.targets[1] if len(gate.targets) > 1 else 1
        theta = gate.parameter or 0
        return (
            f"h {t(q0)}; h {t(q1)}; cx {t(q0)}, {t(q1)}; "
            f"rz({theta}) {t(q1)}; cx {t(q0)}, {t(q1)}; h {t(q0)}; h {t(q1)};"
        )
    if gate.kind == "RYY":
        # RYY(θ) q0,q1 → rx(pi/2) q0; rx(pi/2) q1; cx q0,q1; rz(θ) q1; cx q0,q1; rx(-pi/2) q0; rx(-pi/2) q1;
        q0 = gate.targets[0]
        q1 = gate.targets[1] if len(gate.targets) > 1 else 1
        theta = gate.parameter or 0
        return (
            f"rx(pi/2) {t(q0)}; rx(pi/2) {t(q1)}; cx {t(q0)}, {t(q1)}; "
            f"rz({theta}) {t(q1)}; cx {t(q0)}, {t(q1)}; rx(-pi/2) {t(q0)}; rx(-pi/2) {t(q1)};"
        )
    if gate.kind == "custom":
        return f"// custom gate: {gate.custom_name or 'unknown'} on {', '.join(t(idx) for idx in gate.targets)};"

    return f"// unknown gate: {gate.kind}"


def _infer_qubit_count(machine: QMachineDef) -> int:
    # 1. Explicit qubits list in context: qubits = [q0, q1] → 2
    n_value = None
    has_ancilla = False
    qubits_list_length = None

    for field in machine.context:
        if field.name == "n" and isinstance(field.type, QTypeScalar) and field.type.kind == "int":
            try:
                n_value = int(field.default_value) if field.default_value else None
            except (ValueError, TypeError):
                n_value = None
        if field.name == "ancilla" and isinstance(field.type, QTypeQubit):
            has_ancilla = True
        if field.name == "qubits" and isinstance(field.type, QTypeList):
            if field.default_value:
                items = re.findall(r"q\d+", field.default_value)
                if items:
                    qubits_list_length = len(items)

    if n_value is not None and has_ancilla:
        return n_value + 1
    if qubits_list_length is not None:
        return qubits_list_length

    # 2. Bitstring-style state names: |00> → 2 qubits
    max_bits = 0
    for state in machine.states:
        m = re.search(r"\|([01]+)>", state.name)
        if m:
            max_bits = max(max_bits, len(m.group(1)))
    for state in machine.states:
        if state.state_expression:
            for m in re.finditer(r"\|([01]+)>", state.state_expression):
                max_bits = max(max_bits, len(m.group(1)))
    for guard in machine.guards:
        if guard.expression.kind == "probability":
            max_bits = max(max_bits, len(guard.expression.outcome.bitstring))
    return max_bits or 1
