"""Q-Orca Qiskit compiler — compiles QMachineDef → Qiskit Python script."""

import re

from q_orca.ast import QMachineDef, QuantumGate
from dataclasses import dataclass


DEFAULT_SHOTS = 1024


@dataclass
class QSimulationOptions:
    analytic: bool = True
    shots: int = DEFAULT_SHOTS
    verbose: bool = False
    skip_qutip: bool = False
    run: bool = False


def compile_to_qiskit(machine: QMachineDef, options: QSimulationOptions) -> str:
    lines = []

    lines.append("# Generated by Q-Orca compiler")
    lines.append(f"# Machine: {machine.name}")
    lines.append("")

    lines.append("import json")
    lines.append("import sys")
    lines.append("import numpy as np")
    lines.append("")
    lines.append("from qiskit import QuantumCircuit")
    lines.append("from qiskit.quantum_info import Statevector")
    lines.append("from qiskit.providers.basic_provider import BasicSimulator")
    lines.append("")

    if not options.skip_qutip:
        lines.append("# QuTiP verification (optional)")
        lines.append("try:")
        lines.append("    import qutip")
        lines.append("    HAS_QUTIP = True")
        lines.append("except ImportError:")
        lines.append("    HAS_QUTIP = False")
        lines.append("")

    qubit_count = _infer_qubit_count(machine)
    lines.append(f"qubit_count = {qubit_count}")
    lines.append(f"qc = QuantumCircuit({qubit_count})")
    lines.append("")

    gate_sequence = _extract_gate_sequence(machine)

    lines.append("# Gate sequence from state machine")
    for action_name, gate, comment in gate_sequence:
        if comment:
            lines.append(f"# {comment}")
        if gate:
            lines.append(_gate_to_qiskit(gate))

    if options.analytic:
        lines.append("")
        lines.append("# Simulation (analytic)")
        lines.append("sv = Statevector(qc)")
        lines.append("probs = sv.probabilities()")
        lines.append("num_qubits = qc.num_qubits")
        lines.append('bitstrings = [format(i, f"0{num_qubits}b") for i in range(2**num_qubits)]')
        lines.append("prob_dict = dict(zip(bitstrings, probs))")
    else:
        lines.append("")
        lines.append(f"# Simulation ({options.shots} shots)")
        lines.append(f"shots = {options.shots}")
        lines.append("# Add measurements for shots-based simulation")
        lines.append("qc_shots = QuantumCircuit(qubit_count, qubit_count)")
        lines.append("qc_shots.compose(qc, inplace=True)")
        lines.append("for i in range(qubit_count):")
        lines.append("    qc_shots.measure(i, i)")
        lines.append("backend = BasicSimulator()")
        lines.append("job = backend.run(qc_shots, shots=shots)")
        lines.append("counts = job.result().get_counts(qc_shots)")

    if not options.skip_qutip:
        lines.append("")
        lines.append("# QuTiP Verification")
        lines.append("qutip_result = None")
        lines.append("if HAS_QUTIP:")
        lines.append("    qutip_errors = []")
        lines.append("    unitarity_verified = False")
        lines.append("    entanglement_verified = False")
        lines.append("    schmidt_rank = None")
        lines.append("")
        lines.append("    unitary_matrix = None")
        lines.append("    try:")
        lines.append("        unitary_ops = qc.unitary_matrix()")
        lines.append("        unitary_matrix = unitary_ops.data.tolist()")
        lines.append("    except Exception:")
        lines.append("        qutip_errors.append('Could not extract unitary matrix')")
        lines.append("")
        lines.append("    if unitary_matrix is not None:")
        lines.append("        U = np.array(unitary_matrix)")
        lines.append("        U_dagger = np.conj(U.T)")
        lines.append("        product = np.dot(U, U_dagger)")
        lines.append("        identity = np.eye(len(U))")
        lines.append("        unitarity_error = np.linalg.norm(product - identity)")
        lines.append("        unitarity_verified = unitarity_error < 1e-6")
        lines.append("        if not unitarity_verified:")
        lines.append("            qutip_errors.append(f'Unitarity error: {unitarity_error}')")
        lines.append("")
        lines.append("    try:")
        lines.append("        if sv is not None and len(sv.data) > 0:")
        lines.append("            psi = sv.data.reshape(-1)")
        lines.append("            if len(psi) == 4:")
        lines.append("                psi_2q = psi.reshape(2, 2)")
        lines.append("                s = np.linalg.svd(psi_2q, compute_uv=False)")
        lines.append("                schmidt_rank = int(np.sum(s > 1e-6))")
        lines.append("                entanglement_verified = schmidt_rank > 1")
        lines.append("    except Exception as e:")
        lines.append("        qutip_errors.append(f'Schmidt analysis failed: {e}')")
        lines.append("")
        lines.append("    qutip_result = {")
        lines.append('        "unitarityVerified": unitarity_verified,')
        lines.append('        "entanglementVerified": entanglement_verified,')
        lines.append("        'schmidtRank': schmidt_rank,")
        lines.append("        'errors': qutip_errors")
        lines.append("    }")
        lines.append("else:")
        lines.append("    qutip_result = {'error': 'QuTiP not installed', 'unitarityVerified': False, 'entanglementVerified': False, 'errors': ['QuTiP not available']}")

    lines.append("")
    lines.append("# Build result")
    lines.append("result = {")
    lines.append(f'    "machine": "{machine.name}",')
    lines.append('    "success": True,')
    lines.append('    "superpositionLeaked": False,')
    lines.append('    "leakDetails": [],')

    if options.analytic:
        lines.append('    "probabilities": prob_dict,')
    else:
        lines.append('    "counts": counts,')

    if not options.skip_qutip:
        lines.append('    "qutipVerification": qutip_result,')

    lines.append("}")
    lines.append("")
    lines.append("print(json.dumps(result, indent=2))")

    return "\n".join(lines)


def _extract_gate_sequence(machine: QMachineDef) -> list:
    steps = []
    action_map = {a.name: a for a in machine.actions}

    initial = next((s for s in machine.states if s.is_initial), None)
    if not initial:
        return steps

    visited = set()
    queue = [initial.name]

    while queue:
        current = queue.pop(0)
        if current in visited:
            continue
        visited.add(current)

        outgoing = [t for t in machine.transitions if t.source == current]

        for t in outgoing:
            if t.action:
                action = action_map.get(t.action)
                if action:
                    steps.append((t.action, action.gate, f"{t.source} --{t.event}--> {t.target}"))

            is_measure = "measure" in t.event.lower() or "collapse" in t.event.lower()
            if not is_measure and t.target not in visited:
                queue.append(t.target)

    return steps


def _gate_to_qiskit(gate: QuantumGate) -> str:
    if gate.kind == "H":
        return f"qc.h({gate.targets[0]})"
    if gate.kind == "X":
        return f"qc.x({gate.targets[0]})"
    if gate.kind == "Y":
        return f"qc.y({gate.targets[0]})"
    if gate.kind == "Z":
        return f"qc.z({gate.targets[0]})"
    if gate.kind == "T":
        return f"qc.t({gate.targets[0]})"
    if gate.kind == "S":
        return f"qc.s({gate.targets[0]})"
    if gate.kind == "CNOT":
        ctrl = gate.controls[0] if gate.controls else 0
        return f"qc.cx({ctrl}, {gate.targets[0]})"
    if gate.kind == "CZ":
        ctrl = gate.controls[0] if gate.controls else 0
        return f"qc.cz({ctrl}, {gate.targets[0]})"
    if gate.kind == "SWAP":
        return f"qc.swap({gate.targets[0]}, {gate.targets[1] if len(gate.targets) > 1 else 1})"
    if gate.kind == "Rx":
        return f"qc.rx({gate.parameter or 0}, {gate.targets[0]})"
    if gate.kind == "Ry":
        return f"qc.ry({gate.parameter or 0}, {gate.targets[0]})"
    if gate.kind == "Rz":
        return f"qc.rz({gate.parameter or 0}, {gate.targets[0]})"
    if gate.kind == "CCNOT":
        ctrls = gate.controls or [0, 1]
        c1 = ctrls[1] if len(ctrls) > 1 else 1
        return f"qc.ccx({ctrls[0]}, {c1}, {gate.targets[0]})"
    if gate.kind == "CSWAP":
        ctrl = gate.controls[0] if gate.controls else 0
        t1 = gate.targets[1] if len(gate.targets) > 1 else 2
        return f"qc.cswap({ctrl}, {gate.targets[0]}, {t1})"
    if gate.kind == "custom":
        return f"# custom gate: {gate.custom_name or 'unknown'} on qubits {gate.targets}"
    return f"# unknown gate: {gate.kind}"


def _infer_qubit_count(machine: QMachineDef) -> int:
    max_bits = 0
    for state in machine.states:
        m = re.search(r"\|([01]+)>", state.name)
        if m:
            max_bits = max(max_bits, len(m.group(1)))
    for state in machine.states:
        if state.state_expression:
            for m in re.finditer(r"\|([01]+)>", state.state_expression):
                max_bits = max(max_bits, len(m.group(1)))
    for guard in machine.guards:
        if guard.expression.kind == "probability":
            max_bits = max(max_bits, len(guard.expression.outcome.bitstring))
    return max_bits or 1
